[package]
name = "hayabusa"
version = "2.10.1"
repository = "https://github.com/Yamato-Security/hayabusa"
authors = ["Yamato Security @SecurityYamato"]
edition = "2021"
rust-version = "1.73.0"
include = ["src/**/*", "LICENSE.txt", "README.md", "CHANGELOG.md"]

[dependencies]
itertools = "*"
dashmap = "*"
clap = { version = "4.*", features = ["derive", "cargo", "color"]}
evtx = { git = "https://github.com/Yamato-Security/hayabusa-evtx.git" , features = ["fast-alloc"] , rev = "00ec9cd" } # 0.8.7 2023/11/12 update
quick-xml = {version = "0.*", features = ["serialize"] }
serde = { version = "1.*", features = ["derive"] }
serde_json = { version = "1.0"}
serde_derive = "1.*"
regex = "1"
csv = "1.2.*"
base64 = "*"
flate2 = "1.*"
lazy_static = "1.4.*"
chrono = "0.4.*"
yaml-rust = "0.4.*"
tokio = { version = "1", features = ["full"] }
num_cpus = "1.*"
downcast-rs = "1.*"
indicatif = "*"
hashbrown = "0.14.*"
hex = "0.4.*"
git2 = "0.*"
termcolor = "*"
krapslog = "0.5"
terminal_size = "*"
bytesize = "1.*"
lock_api = "0.4.*"
crossbeam-utils = "0.8.*"
num-format = "*"
comfy-table = "7.*"
pulldown-cmark = { version = "0.9.*", default-features = false, features = ["simd"] }
horrorshow = "0.8.*"
mimalloc = { version = "*", default-features = false }
libmimalloc-sys = { version = "*",  features = ["extended"] }
nested="*"
compact_str = "0.7.*"
ureq = "*"
mockall = "*"
maxminddb = "0.*"
cidr-utils = "0.*"
aho-corasick = "*"
memchr = "2.*"
num = "0.4.0"
indexmap = "2.*"
dialoguer = "*"

[profile.dev]
debug = 0

[dev-dependencies]
rand = "0.8.*"

[target.'cfg(windows)'.dependencies]
is_elevated = "0.1.*"

[target.'cfg(unix)'.dependencies] #Mac and Linux
openssl = { version = "0.9.24", features = ["vendored"] }  #vendored is needed to compile statically.

[profile.release]
lto = true
strip = "symbols"
