[package]
name = "hayabusa"
version = "1.9.1"
authors = ["Yamato Security @SecurityYamato"]
edition = "2021"
rust-version = "1.65.0"

[dependencies]
itertools = "*"
dashmap = "*"
clap = { version = "4.*", features = ["derive", "cargo", "color"]}
evtx = { git = "https://github.com/Yamato-Security/hayabusa-evtx.git" , features = ["fast-alloc"] , rev = "9c1576b" } # 0.8.3 2022/12/20 update
quick-xml = {version = "0.26.*", features = ["serialize"] }
serde = { version = "1.*", features = ["derive"] }
serde_json = { version = "1.0"}
serde_derive = "1.*"
regex = "1"
csv = "1.1.*"
base64 = "*"
flate2 = "1.*"
lazy_static = "1.4.*"
chrono = "0.4.*"
yaml-rust = "0.4.*"
linked-hash-map = "0.5.*"
tokio = { version = "1", features = ["full"] }
num_cpus = "1.*"
downcast-rs = "1.*"
hhmmss = "*"
pbr = "*"
hashbrown = "0.13.*"
hex = "0.4.*"
git2 = "0.*"
termcolor = "*"
krapslog = "*"
terminal_size = "*"
bytesize = "1.*"
hyper = "0.14.*"
lock_api = "0.4.*"
crossbeam-utils = "0.8.*"
num-format = "*"
comfy-table = "6.*"
pulldown-cmark = { version = "0.9.*", default-features = false, features = ["simd"] }
reqwest = {version = "0.11.*", features = ["blocking", "json"]}
horrorshow = "0.8.*"
mimalloc = { version = "*", default-features = false }
libmimalloc-sys = { version = "*",  features = ["extended"] }
nested="*"
compact_str = "0.6.*"

[dev-dependencies]
rand = "0.8.*"

[target.'cfg(windows)'.dependencies]
is_elevated = "0.1.*"

[target.'cfg(unix)'.dependencies] #Mac and Linux
openssl = { version = "*", features = ["vendored"] }  #vendored is needed to compile statically.

[profile.release]
lto = true
strip = "symbols"