[package]
name = "hayabusa"
version = "1.1.0"
authors = ["Yamato Security @SecurityYamato"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evtx = { git = "https://github.com/omerbenamram/evtx.git" , rev = "95a8ca6" , features = ["fast-alloc"]}
quick-xml = {version = "0.22.0", features = ["serialize"] }
serde = { version = "1.0.*", features = ["derive"] }
serde_json = { version = "1.0"}
serde_derive = "1.0.*"
clap = "2.*"
regex = "1.5.*"
csv = "1.1.*"
base64 = "*"
flate2 = "1.0.*"
lazy_static = "1.4.0"
chrono = "0.4.19"
yaml-rust = "0.4.*"
linked-hash-map = "0.5.*"
tokio = { version = "1", features = ["full"] }
num_cpus = "1.13.*"
mopa = "0.2.*"
slack-hook = "0.8"
dotenv = "0.15.*"
hhmmss = "*"
pbr = "*"
hashbrown = "0.12.*"
colored = "2.*"
hex = "0.4.*"
is_elevated = {git="https://github.com/yandexx/is_elevated", rev="aa04209"}

[profile.release]
lto = true