
title: Invoke-Obfuscation CLIP+ Launcher
author: Jonathan Cheong, oscd.community
date: 2020/10/13
description: Detects Obfuscated use of Clip.exe to execute PowerShell
detection:
  SELECTION_1:
    ServiceFileName|re: .*cmd.{0,5}(?:/c|/r).+clip(?:\.exe)?.{0,4}&&.+clipboard]::\(\s\\"\{\d\}.+\-f.+"
  SELECTION_2:
    EventID: 4697
  condition: (SELECTION_1 and SELECTION_2)
falsepositives:
- Unknown
id: 4edf51e1-cb83-4e1a-bc39-800e396068e3
level: high
logsource:
  product: windows
  service: security
modified: 2021/09/16
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: f7385ee2-0e0c-11eb-adc1-0242ac120002
  type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
ruletype: SIGMA
