
title: Invoke-Obfuscation STDIN+ Launcher
author: Jonathan Cheong, oscd.community
date: 2020/10/15
description: Detects Obfuscated use of stdin to execute PowerShell
detection:
  SELECTION_1:
    ServiceFileName|re: .*cmd.{0,5}(?:/c|/r).+powershell.+(?:\$\{?input\}?|noexit).+"
  SELECTION_2:
    EventID: 4697
  condition: (SELECTION_1 and SELECTION_2)
falsepositives:
- Unknown
id: 0c718a5e-4284-4fb9-b4d9-b9a50b3a1974
level: high
logsource:
  product: windows
  service: security
modified: 2021/09/17
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: 72862bf2-0eb1-11eb-adc1-0242ac120002
  type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
