title: New Lolbin Process by Office Applications
author: Vadim Khrykov (ThreatIntel), Cyb3rEng (Rule)
date: 2021/08/23
description: This rule will monitor any office apps that spins up a new LOLBin process.
    This activity is pretty suspicious and should be investigated.
detection:
    SELECTION_1:
        Image: '*regsvr32'
    SELECTION_2:
        Image: '*rundll32'
    SELECTION_3:
        Image: '*msiexec'
    SELECTION_4:
        Image: '*mshta'
    SELECTION_5:
        Image: '*verclsid'
    SELECTION_6:
        ParentImage: '*winword.exe'
    SELECTION_7:
        ParentImage: '*excel.exe'
    SELECTION_8:
        ParentImage: '*powerpnt.exe'
    condition: ((SELECTION_1 or SELECTION_2 or SELECTION_3 or SELECTION_4 or SELECTION_5)
        and (SELECTION_6 or SELECTION_7 or SELECTION_8))
falsepositives:
- Unknown
id: 23daeb52-e6eb-493c-8607-c4f0246cb7d8
level: high
logsource:
    category: process_creation
    product: Windows
references:
- https://thedfirreport.com/2021/03/29/sodinokibi-aka-revil-ransomware/
- https://github.com/vadim-hunter/Detection-Ideas-Rules/blob/main/Threat%20Intelligence/The%20DFIR%20Report/20210329_Sodinokibi_(aka_REvil)_Ransomware.yaml
status: experimental
tags:
- attack.t1204.002
- attack.t1047
- attack.t1218.010
- attack.execution
- attack.defense_evasion
yml_filename: process_creation_lolbins_by_office_applications.yml
yml_path: /home/itib/git/sigma/rules/windows/process_creation

