
title: Office Security Settings Changed
author: Trent Liffick (@tliffick)
date: 2020/05/22
description: Detects registry changes to Office macro settings
detection:
  SELECTION_1:
    EventID: 12
  SELECTION_2:
    EventID: 13
  SELECTION_3:
    EventID: 14
  SELECTION_4:
    TargetObject:
    - '*\Security\Trusted Documents\TrustRecords'
    - '*\Security\AccessVBOM'
    - '*\Security\VBAWarnings'
  condition: ((SELECTION_1 or SELECTION_2 or SELECTION_3) and SELECTION_4)
falsepositives:
- Valid Macros and/or internal documents
id: a166f74e-bf44-409d-b9ba-ea4b2dd8b3cd
level: high
logsource:
  category: registry_event
  product: windows
modified: 2021/07/12
references:
- Internal Research
- https://www.mcafee.com/blogs/other-blogs/mcafee-labs/zloader-with-a-new-infection-technique/
status: experimental
tags:
- attack.defense_evasion
- attack.t1112
ruletype: SIGMA
